# Routing
routingType:	yml

# Template Engine
template:    twig

# database configuration
database:
    user:		root
    password:		
    dbname:		anthill
    host:		127.0.0.1
    engine:		mysql

# language (tool development)
language:    fr

# environnement (dev | prod)
environnement:    dev

# Permit to check if a project is already started
existingproject:    true

salt: zZZLo_ivIdf(QkZh